### ISSUE TITLE
Update Logo design

### ISSUE THREAD

**Issue by Seroft-solution** [Seroft-solution/PharmacyHub-React#13]
I just updated the logo, hopefully it would be better now.
.
![1694985730546.png](https://github.com/Seroft-solution/PharmacyHub-React/assets/144958859/4e7b6036-93b2-4e29-84de-47ff243077e8)

....

**Comment by syedus06** [comment]
Yes this is better now. We can use this.

@rabia3010 , you can replace jpeg to this png.

**Comment by Seroft-solution** [comment]
Rabia kindly do tell us when it is completed. We are waiting
